-- Generated by scripts/generate-replacement-migration.mjs.
-- Adds physical sticker variants without changing the album's 980 logical slots.

alter table public.stickers
  add column if not exists slot_id uuid,
  add column if not exists variant_type text not null default 'original';

update public.stickers
set slot_id = id
where slot_id is null;

alter table public.stickers
  alter column slot_id set not null,
  drop constraint if exists stickers_section_id_position_key,
  drop constraint if exists stickers_slot_id_fkey,
  drop constraint if exists stickers_variant_type_check,
  drop constraint if exists stickers_slot_consistency_check,
  add constraint stickers_slot_id_fkey foreign key (slot_id) references public.stickers(id) on delete cascade,
  add constraint stickers_variant_type_check check (variant_type in ('original', 'replacement')),
  add constraint stickers_slot_consistency_check check (
    (variant_type = 'original' and slot_id = id)
    or (variant_type = 'replacement' and slot_id <> id)
  );

create unique index if not exists stickers_original_section_position_unique
  on public.stickers (section_id, position)
  where variant_type = 'original';

create index if not exists stickers_slot_id_idx on public.stickers(slot_id);

with target_album as (
  select id from public.albums where slug = 'copa-2026'
), source_replacements (outgoing_label, code, incoming_label) as (
  values
    ('Estévão', 'BRA 20 S', 'Igor Thiago'),
    ('Rodrygo', 'BRA 15 S', 'Neymar Jr'),
    ('Éder Militão', 'BRA 5 S', 'Alex Sandro'),
    ('Bento', 'BRA 3 S', 'Weverton'),
    ('Sébastien Haller', 'CIV 16 S', 'Elve Wahi'),
    ('Willy Boly', 'CIV 7 S', 'Guéla Doué'),
    ('Kamal Miller', 'CAN 9 S', 'Alfie Jones'),
    ('Samuel Adekugbe', 'CAN 5 S', 'Joel Waterman'),
    ('Vasil Kusej', 'CZE 16 S', 'Vladimír Darida'),
    ('Lovro Majer', 'CRO 12 S', 'Nikola Vlašić'),
    ('Bebe', 'CPV 20 S', 'Nuno da Costa'),
    ('Patrick Andrade', 'CPV 11 S', 'Labos Duarte'),
    ('Mohamed Hamdy', 'EGY 4 S', 'Mohamed Abdelmonem'),
    ('Leonardo Campana', 'ECU 15 S', 'Anthony Valencia'),
    ('Vaclav Cerny', 'CZE 18 S', 'Mojmír Chytil'),
    ('Matej Vydra', 'CZE 15 S', 'David Douděra'),
    ('Trent Alexander-Arnold', 'ENG 6 S', 'Nico O''Reilly'),
    ('Osama Faisal', 'EGY 16 S', 'Ibrahim Adel'),
    ('Mostafa Mohamed', 'EGY 18 S', 'Haissem Hassan'),
    ('Khaled Sobhi', 'EGY 6 S', 'Mahmoud Saber'),
    ('Jean-Philippe Gbamin', 'CIV 14 S', 'Nicolas Pépé'),
    ('João Pedro', 'BRA 16 S', 'Endrick'),
    ('Lewis Miller', 'AUS 9 S', 'Jason Geria'),
    ('Serge Gnabry', 'GER 16 S', 'Aleksandar Pavlović'),
    ('Dean Huijsen', 'ESP 5 S', 'Alejandro Grimaldo'),
    ('Cole Palmer', 'ENG 12 S', 'Eberechi Eze'),
    ('Franjo Ivanovic', 'CRO 20 S', 'Igor Matanović'),
    ('Abdulrahman Al-Aboud', 'KSA 17 S', 'Sultan Mandash'),
    ('Shuto Machino', 'JPN 17 S', 'Yuito Suzuki'),
    ('Omid Noorafkan', 'IRN 14 S', 'Amir Mohammad Razzaghinia'),
    ('Tariq Lamptey', 'GHA 3 S', 'Benjamin Asare'),
    ('Siyabonga Ngezana', 'RSA 8 S', 'Ime Okon'),
    ('Jeremie Frimpong', 'NED 8 S', 'Quinten Timber'),
    ('Érick Sánchez', 'MEX 14 S', 'Brian Gutiérrez'),
    ('Eliesse Ben Seghir', 'MAR 12 S', 'Neil El Aynaoui'),
    ('Khojimat Erkinov', 'UZB 15 S', 'Akmal Mozgovoy'),
    ('Tanner Tessmann', 'USA 9 S', 'Gio Reyna'),
    ('Sayfallah Ltaief', 'TUN 19 S', 'Sebastian Tounekti'),
    ('Hugo Larsson', 'SWE 9 S', 'Besfort Zeneli'),
    ('Xavi Simons', 'NED 15 S', 'Noa Lang'),
    ('Hirving Lozano', 'MEX 15 S', 'Armando González'),
    ('Diego Lainez', 'MEX 8 S', 'Gilberto Mora'),
    ('Carlos Rodriguez', 'MEX 9 S', 'Álvaro Fidalgo'),
    ('Tarek Salman', 'QAT 8 S', 'Ayoub Aloui'),
    ('Angel Romero', 'PAR 19 S', 'Álex Arce'),
    ('Mathías Villasanti', 'PAR 9 S', 'Braian Ojeda'),
    ('Aron Dønnum', 'NOR 17 S', 'Jens Petter Hauge'),
    ('Bathusi Aubaas', 'RSA 14 S', 'Themba Zwane'),
    ('Sipho Mbule', 'RSA 16 S', 'Jayden Adams'),
    ('Ahmed Al Ganehi', 'QAT 19 S', 'Mohammed Muntari'),
    ('Mohammed Waad', 'QAT 14 S', 'Jassem Gaber'),
    ('Emil Holm', 'SWE 5 S', 'Carl Starfelt'),
    ('Boulaye Dia', 'SEN 17 S', 'Ibrahim Mbaye'),
    ('Billy Gilmour', 'SCO 12 S', 'Nathan Patterson'),
    ('Mohau Nkota', 'RSA 19 S', 'Relebohile Mofokeng'),
    ('Yassine Meriah', 'TUN 6 S', 'Omar Rekik'),
    ('Bechir Ben Said', 'TUN 2 S', 'Abdelmouhib Chamakh'),
    ('Roony Bardghji', 'SWE 16 S', 'Benjamin Nygren'),
    ('Dejan Kulusevski', 'SWE 17 S', 'Alexander Bernhardsson'),
    ('Naim Sliti', 'TUN 20 S', 'Mortadha Ben Ouanes'),
    ('Mohamed Ali Ben Romdhane', 'TUN 12 S', 'Mohamed Belhadj Mahmoud'),
    ('Aissa Laidouni', 'TUN 10 S', 'Rani Khedira'),
    ('Ferjani Sassi', 'TUN 11 S', 'Anis Ben Slimane'),
    ('Azizbek Turgunboev', 'UZB 14 S', 'Azizjon Ganiev'),
    ('Husniddin Aliqulov', 'UZB 6 S', 'Jakhongir Urozov'),
    ('Diego Luna', 'USA 14 S', 'Sebastian Berhalter'),
    ('Nahitan Nandez', 'URU 9 S', 'Matías Viña'),
    ('Ismael Bennacer', 'ALG 8 S', 'Ibrahim Maza'),
    ('Youcef Atal', 'ALG 4 S', 'Rafik Belghali'),
    ('Alexis Guendouz', 'ALG 2 S', 'Luca Zidane'),
    ('Joe Gauci', 'AUS 3 S', 'Paul Izzo'),
    ('Franco Mastantuono', 'ARG 15 S', 'Giovani Lo Celso'),
    ('Said Benrahma', 'ALG 16 S', 'Adil Boulbina'),
    ('Baghdad Bounedjah', 'ALG 19 S', 'Farès Ghedjemis'),
    ('Loïs Openda', 'BEL 19 S', 'Dodi Lukébakio'),
    ('Craig Goodwin', 'AUS 17 S', 'Nishan Velupillay'),
    ('Riley McGree', 'AUS 12 S', 'Ajdin Hrustić'),
    ('Patrick Yazbek', 'AUS 16 S', 'Paul Okon-Engstler'),
    ('Álvaro Morata', 'ESP 19 S', 'Yeremy Pino'),
    ('Dani Carvajal', 'ESP 7 S', 'Marcos Llorente'),
    ('Robin Le Normand', 'ESP 3 S', 'Pau Cubarsí'),
    ('Phil Foden', 'ENG 16 S', 'Noni Madueke'),
    ('Marc-André ter Stegen', 'GER 2 S', 'Manuel Neuer'),
    ('Hugo Ekitike', 'FRA 19 S', 'Marcus Thuram'),
    ('Kingsley Coman', 'FRA 18 S', 'Rayan Cherki'),
    ('Eduardo Camavinga', 'FRA 10 S', 'N''Golo Kanté'),
    ('Alexander Djiku', 'GHA 6 S', 'Jonas Adjetey'),
    ('Karim Adeyemi', 'GER 19 S', 'Deniz Undav'),
    ('Maximilian Mittelstadt', 'GER 9 S', 'Angelo Stiller'),
    ('Ridle Baku', 'GER 8 S', 'Malick Thiaw'),
    ('André Ayew', 'GHA 17 S', 'Ernest Nuamah'),
    ('Mohammed Kudus', 'GHA 14 S', 'Christopher Bonsu Baah'),
    ('Salis Abdul Samed', 'GHA 11 S', 'Kwasi Sibo'),
    ('Mohammed Salisu', 'GHA 4 S', 'Kojo Peprah Oppong'),
    ('Christopher Attys', 'HAI 14 S', 'Wilson Isidor'),
    ('Garven Metusala', 'HAI 8 S', 'Wilguens Paugain'),
    ('Osman Bukari', 'GHA 19 S', 'Prince Adu'),
    ('Joseph Paintsil', 'GHA 18 S', 'Brandon Thomas-Asante'),
    ('Ali Gholizadeh', 'IRN 20 S', 'Amirhossein Hosseinzadeh'),
    ('Sardar Azmoun', 'IRN 17 S', 'Ali Alipour'),
    ('Sadegh Moharrami', 'IRN 9 S', 'Ali Nemati'),
    ('Morteza Pouraliganji', 'IRN 3 S', 'Arya Yousefi'),
    ('Yuki Soma', 'JPN 9 S', 'Wataru Endo'),
    ('Henry Heroki Mochizuki', 'JPN 3 S', 'Hiroki Ito'),
    ('Yazan Al-Naimat', 'JOR 16 S', 'Odeh Fakhoury'),
    ('Osama Rashid', 'IRQ 17 S', 'Kevin Yakob'),
    ('Abdulrahman Al-Sanbi', 'KSA 3 S', 'Abdullelah Al Amri'),
    ('Yu-min Cho', 'KOR 5 S', 'Moonhwan Kim'),
    ('Myung-jae Lee', 'KOR 9 S', 'Taehyeon Kim'),
    ('Takumi Minamino', 'JPN 16 S', 'Daizen Maeda'),
    ('Jawad El Yamiq', 'MAR 8 S', 'Anass Salah-Eddine'),
    ('Romain Saïss', 'MAR 7 S', 'Issa Diop'),
    ('Saleh Abu Alshamat', 'KSA 14 S', 'Mohamed Kanno'),
    ('Marwan Alsahafi', 'KSA 15 S', 'Ali Majrashi'),
    ('Marcel Ruiz', 'MEX 12 S', 'Érik Lira'),
    ('Luis Malagón', 'MEX 2 S', 'Guillermo Ochoa'),
    ('Youssef En-Nesyri', 'MAR 16 S', 'Chemsdine Talbi'),
    ('Adam Masina', 'MAR 9 S', 'Chadi Riad')
), original_slots as (
  select stickers.*
  from public.stickers
  join target_album on target_album.id = stickers.album_id
  where stickers.variant_type = 'original'
)
insert into public.stickers (
  album_id, section_id, code, label, position, slot_id, variant_type
)
select
  original_slots.album_id,
  original_slots.section_id,
  source_replacements.code,
  source_replacements.incoming_label,
  original_slots.position,
  original_slots.id,
  'replacement'
from source_replacements
join original_slots on original_slots.label = source_replacements.outgoing_label
on conflict (album_id, code) do update set
  section_id = excluded.section_id,
  label = excluded.label,
  position = excluded.position,
  slot_id = excluded.slot_id,
  variant_type = excluded.variant_type;

do $$
declare
  replacement_count integer;
begin
  select count(*) into replacement_count
  from public.stickers
  join public.albums on albums.id = stickers.album_id
  where albums.slug = 'copa-2026'
    and stickers.variant_type = 'replacement';

  if replacement_count <> 118 then
    raise exception 'Expected 118 replacement stickers, found %', replacement_count;
  end if;
end;
$$;

-- Public lists continue to expose only the selected missing/duplicate view.
-- Missing is calculated per logical slot; duplicates are calculated per
-- physical variant, so owning one original and one replacement is not a repeat.
create or replace function public.get_collection_share(share_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'ownerName', coalesce(nullif(profiles.display_name, ''), nullif(profiles.username, ''), 'Colecionador ColaFig'),
    'albumSlug', albums.slug,
    'albumName', albums.name,
    'viewType', collection_shares.view_type,
    'items', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'code', shared_items.code,
          'label', shared_items.label,
          'sectionName', shared_items.section_name,
          'quantity', shared_items.quantity
        ) order by shared_items.section_position, shared_items.sticker_position, shared_items.variant_type
      ) filter (where shared_items.code is not null),
      '[]'::jsonb
    )
  )
  from public.collection_shares
  join public.albums on albums.id = collection_shares.album_id and albums.is_active = true
  left join public.profiles on profiles.id = collection_shares.user_id
  left join lateral (
    select
      stickers.code,
      stickers.label,
      sections.name as section_name,
      sections.position as section_position,
      stickers.position as sticker_position,
      stickers.variant_type,
      coalesce(collections.quantity, 0)::smallint as quantity
    from public.stickers
    join public.sections on sections.id = stickers.section_id
    left join public.collections
      on collections.user_id = collection_shares.user_id
      and collections.sticker_id = stickers.id
    where stickers.album_id = albums.id
      and (
        (
          collection_shares.view_type = 'missing'
          and stickers.variant_type = 'original'
          and not exists (
            select 1
            from public.stickers as slot_variant
            join public.collections as slot_collection
              on slot_collection.sticker_id = slot_variant.id
              and slot_collection.user_id = collection_shares.user_id
              and slot_collection.quantity > 0
            where slot_variant.slot_id = stickers.id
          )
        )
        or (
          collection_shares.view_type = 'duplicates'
          and coalesce(collections.quantity, 0) > 1
        )
      )
  ) as shared_items on true
  where collection_shares.token = share_token
    and collection_shares.revoked_at is null
  group by collection_shares.id, profiles.display_name, profiles.username, albums.id;
$$;

revoke all on function public.get_collection_share(uuid) from public;
grant execute on function public.get_collection_share(uuid) to anon, authenticated;
